swade.rabbitmq.listener.enabled=false
minio.endpoint=http://localhost:9000
minio.access.key=minio
minio.secret.key=minio123
minio.bucket.name=mri-files
mri.minio.heatmap-bucket=heatmaps
mri.minio.report-bucket=reports

